[meta]
name = "Milk Medals"
author = "J_unki"
category = "Race"
version = "1.0.0"


[script]
name = "Milk Medals"
id = "MilkMedal"
version = "1.0.0"
optional_dependencies = [ "UltimateMedalsExtended" ]